'use client';

import "../app/globals.css";
import Navbar from "../components/navbar/navbar";
import Script from "next/script";

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Script src="https://kit.fontawesome.com/e5d641a935.js" crossorigin="anonymous"/>
      </body>
    </html>
  )
}
